### PR TITLE
Fix logging

### LINKED ISSUE #293: spdlog not always working
the forwarding of the c++ spdlog to python logging seems not to work always as expected:

one example i came up with now (but there were also other instances/bugs were i encountered this) is the following code:
```
import logging

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger()

import pairinteraction.real as pi

db1 = pi.Database(database_dir="test1")
db2 = pi.Database(database_dir="test2")

import time
time.sleep(1)

pi.KetAtom("Rb", n=60, l=0, m=0.5) 
```

when the last line is removed, there will be no output at all.
However, when the last line is run, I get the expected output:
```
2025-08-12 15:03:37,020 - INFO - Using database directory: [...test1](https://file+.vscode-resource.vscode-cdn.net...test1)
2025-08-12 15:03:37,021 - INFO - Asset            Local     Remote
2025-08-12 15:03:37,021 - INFO - -----------------------------------
2025-08-12 15:03:37,021 - INFO - Using database directory: [...test2](https://file+.vscode-resource.vscode-cdn.net...test2)
2025-08-12 15:03:37,022 - INFO - Asset            Local     Remote
2025-08-12 15:03:37,022 - INFO - -----------------------------------
2025-08-12 15:03:38,070 - INFO - Using database directory: [.../.cache/pairinteraction/database](https://file+.vscode-resource.vscode-cdn.net.../.cache/pairinteraction/database)
2025-08-12 15:03:38,071 - INFO - Asset            Local     Remote
2025-08-12 15:03:38,071 - INFO - -----------------------------------
2025-08-12 15:03:38,071 - INFO - Rb               v1.2  >   N/A
2025-08-12 15:03:38,072 - INFO - Sr87_mqdt        v1.0  >   N/A
2025-08-12 15:03:38,072 - INFO - Sr88_mqdt        v1.1  >   N/A
2025-08-12 15:03:38,072 - INFO - Sr88_singlet     v1.2  >   N/A
2025-08-12 15:03:38,072 - INFO - Sr88_triplet     v1.2  >   N/A
2025-08-12 15:03:38,073 - INFO - Yb171_mqdt       v1.0  >   N/A
2025-08-12 15:03:38,073 - INFO - Yb173_mqdt       v1.0  >   N/A
2025-08-12 15:03:38,073 - INFO - Yb174_mqdt       v1.1  >   N/A
2025-08-12 15:03:38,073 - INFO - misc             v1.2  >   N/A
```

### PR DESCRIPTION
**Pull request by seweber**
Fixes #293

### CODE REVIEW

File: src/cpp/bindings/LoggerBridge.cpp [hunk 1]
```diff
@@ -84,10 +80,12 @@ LoggerBridge::~LoggerBridge() {
...
-    while (log_queue.try_pop(entry)) {
-        entries.push_back(std::move(entry));
+    std::deque<LogEntry> log_queue_local;
+    {
+        std::lock_guard<std::mutex> lock(log_queue_mtx);
+        log_queue_local.swap(log_queue);
     }
-    return entries;
+
+    return std::vector<LogEntry>(std::make_move_iterator(log_queue_local.begin()),
```
Comment (johannes-moegerle) [inline src/cpp/bindings/LoggerBridge.cpp:89]: maybe directly return log_queue_local

Comment (seweber) [reply src/cpp/bindings/LoggerBridge.cpp]: Unfortunately, nanobind ships helpers only for std::vector.

**Review by johannes-moegerle — APPROVED** [review]
